project_id = "ubbparyexygltuyjpdqg"

[functions.send-contact-email]
verify_jwt = false

[functions.send-guide-email]
verify_jwt = false

[functions.send-calculator-estimate]
verify_jwt = false

[functions.get-google-reviews]
verify_jwt = false