// AUTO-GENERATED by @lovable.dev/mcp-js, do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/get-company-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_company_info_default = defineTool({
  name: "get_company_info",
  title: "Get company info",
  description: "Get BoldREMO's contact details, service areas, and consultation process.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      company: "BoldREMO",
      focus: "Luxury bathroom remodeling in Houston, Texas",
      owner: "Stan",
      phone: "(832) 513-5737",
      email: "info@boldremo.com",
      website: "https://www.boldremo.com",
      serviceAreas: ["Houston", "Heights", "Bellaire", "River Oaks", "Kingwood"],
      process: [
        "Free rough estimate",
        "$75 in-home design consult",
        "Detailed proposal and project schedule"
      ],
      cta: "Book Bathroom Consult"
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/get-pricing.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var tiers = [
  {
    title: "Guest / Hall Bathroom Remodel",
    priceRange: "$8,000 \u2013 $15,000",
    description: "Cosmetic updates, tile, fixtures, lighting",
    features: ["New tile flooring", "Updated fixtures", "Modern lighting", "Fresh paint & finishes"]
  },
  {
    title: "Full Bathroom Renovation",
    priceRange: "$18,000 \u2013 $32,000",
    description: "Full demo, layout updates, custom tile",
    features: ["Complete demolition", "Layout modifications", "Custom tile work", "New vanity & storage"]
  },
  {
    title: "Luxury Spa Bathroom",
    priceRange: "$35,000+",
    description: "Heated floors, premium finishes, custom showers",
    features: ["Heated flooring", "Frameless glass shower", "Premium materials", "Smart home features"]
  }
];
var get_pricing_default = defineTool2({
  name: "get_pricing",
  title: "Get remodel pricing tiers",
  description: "Get BoldREMO's typical Houston bathroom remodel packages with price ranges and included work.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(tiers, null, 2) }],
    structuredContent: { tiers }
  })
});

// src/lib/mcp/tools/list-contact-submissions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contact_submissions_default = defineTool3({
  name: "list_contact_submissions",
  title: "List contact submissions",
  description: "List website contact form submissions, newest first. Requires an admin account.",
  inputSchema: {
    limit: z.number().int().default(20).describe("How many submissions to return (max 100)."),
    unread_only: z.boolean().default(false).describe("Only return unread submissions.")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit, unread_only }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 20, 1), 100);
    let query = supabaseForUser(ctx).from("contact_submissions").select("id, first_name, last_name, email, phone, message, is_read, created_at").order("created_at", { ascending: false }).limit(take);
    if (unread_only) query = query.eq("is_read", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { submissions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/mark-submission-read.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var mark_submission_read_default = defineTool4({
  name: "mark_submission_read",
  title: "Mark submission as read",
  description: "Mark a website contact submission as read. Requires an admin account.",
  inputSchema: {
    id: z2.string().describe("The submission id (uuid).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("contact_submissions").update({ is_read: true }).eq("id", id).select("id, is_read");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data || data.length === 0) {
      return { content: [{ type: "text", text: `No submission updated for id ${id}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Submission ${id} marked as read.` }],
      structuredContent: { row: data[0] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ubbparyexygltuyjpdqg";
var mcp_default = defineMcp({
  name: "boldremo-website",
  title: "BoldREMO website",
  version: "0.1.0",
  instructions: "Tools for the BoldREMO luxury bathroom remodeling website (Houston, TX). Use `get_company_info` and `get_pricing` for company, service-area, and package details. Use `list_contact_submissions` and `mark_submission_read` to review website leads (admin accounts only).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_company_info_default, get_pricing_default, list_contact_submissions_default, mark_submission_read_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
